### ISSUE TITLE
Phone not open

### ISSUE THREAD

**Issue by madspenzi** [rdlh/onset-phone#1]
Hello the phone not open in the game just the animated

**Comment by rdlh** [comment]
Hi, could you please send me some server and client logs to investigate?

**Comment by madspenzi** [comment]
no error in the logs

**Comment by rdlh** [comment]
Could you please retry with the new 1.0 version?

Feel free to follow all steps in the wiki

**Comment by madspenzi** [comment]
Vous parler francais ? je nutiliser pas la version 1.0 mais ou est ce que je mets la génération de numero

**Comment by rdlh** [comment]
Ou tu veux, le mieux etant de le mettre a l'endroit ou tu crée les comptes de tes utilisateurs

**Comment by madspenzi** [comment]
ok c'est bon pour moi sa fonctionne merci très bon script manque juste un peut d'application mais je pense que tu bosse dessus très bon travaille bravo

**Comment by rdlh** [comment]
Oui ça va arriver :)
