### ISSUE TITLE
Erreur Téléphone

### ISSUE THREAD

**Issue by bikouz** [rdlh/onset-phone#2]
Lorsque je veux ouvrir le téléphone, dans ma console cela m'affiche : 

[string "onsetrp_addons/phone/server.lua"]:11: attempt to index a nil value (global 'PlayerData')

**Comment by rdlh** [comment]
Est-ce que tu utilise https://github.com/frederic2ec/onsetrp ?

**Comment by bikouz** [comment]
Oui juste je l'ai mis dans un package à coté, c'est pas conseillé ?

**Comment by bikouz** [comment]
Je n'ai pas mis les fichiers : 
Generating phone numbers
Load player's phone_contacts

Un conseil où les mettre ? Merci

**Comment by rdlh** [comment]
Tu peux télécharger la dernière version du script de fred, le téléphone y est intégré :)
