### ISSUE TITLE
Problème Ouverture téléphone

### ISSUE THREAD

**Issue by pymouse231** [rdlh/onset-phone#3]
Salut, j'ai bien mis le tel dans onset puis j'ai mis les truc du wiki dans le packtage puis dans le serv de account j'ai mis la gestion de création de numéro sa ça fonctionne et ça load bien mes contacts (j'ai bien le message dans la console qui dit que c'est load) mais quand j'appuie sur K rien ne ce passe j'ai vérifié les logs serveur il n'y a aucune erreur et dans les logs client non plus. j'ai fait un print client sur le touche k et je vois bien mon print dans les logs ducoup je comprend pas pourquoi ça ne fonctionne pas.
J'utilise la version 1.0.
Merci d'avance

**Comment by rdlh** [comment]
Salut ! Il faut un téléphone dans l'inventaire pour que ça fonctionne :).

Tu peux désactiver cette fonctionnalité en passant `canUsePhoneWithoutPhoneItem` à `false` :)

**Comment by pymouse231** [comment]
Merci c'était bien ça ^^ je suis aveugle ^^
