### ISSUE TITLE
Sauvegarde des messages

### ISSUE THREAD

**Issue by bikouz** [rdlh/onset-phone#4]
Salut, alors tout fonctionne bien, sauvegarde de contact, ouverture du téléphone etc.. Mais pas la sauvegarde des messages. Dès lors de la fermeture et réouverture du téléphone ceux ci disparaissent. Et aucun message dans la console.

**Comment by bikouz** [comment]
La suppression de contact ne marche pas non plus, impossible de cliquer sur Oui (pour confirmer la suppression), mais par contre sur Non ca marche

**Comment by rdlh** [comment]
Hello, tu peux regarder l'implémentation sur [le repo de fred](https://github.com/frederic2ec/onsetrp/commit/00392faf76825b27b079dd387740d931d5efc648) ? Tout à l'air ok ici

**Comment by Owned3D** [comment]
Ayant eu le même soucis, j'ai donc chercher à debug la sauvegarde des message dans la base de données et après quelque minutes de recherche j'ai trouver d'où venais le soucis.


function MessageCreated(player, phone, content)
    local created_at = tostring(os.time(os.date("!*t")))
    local query = mariadb_prepare(sql, "INSERT INTO messages (`id`, `from`, `to`, `content`, `created_at`) VALUES (NULL, '?', '?', '?', '?');", tostring(PlayerData[player].phone_number), phone, content, created_at)

    local playersIds = GetAllPlayers()

    for playerId, v in pairs(playersIds) do
        if PlayerData[playerId].phone_number == phone then
            CallRemoteEvent(playerId, "NewMessage", PlayerData[player].phone_number, phone, content, created_at)
        end
    end
   ====> (Il faut rajoute cet ligne pour l'envoi) mariadb_query(sql, query, NullCallback)
end
AddRemoteEvent("MessageCreated", MessageCreated)

**Comment by bikouz** [comment]
merci :D

**Comment by Dev-Assistance** [comment]
Owned3D cela fonctionne merci à toi !

**Comment by rdlh** [comment]
Updated dans la dernière version sur master ! Merci @Owned3D 🚀 et désolé @bikouz et @Dev-Assistance 😄
