### ISSUE TITLE
Application bancaire

### ISSUE THREAD

**Issue by Dev-Assistance** [rdlh/onset-phone#6]
Bonjour,

Quand je vais dans l'application bancaire, j'ai toujours le même nombre affiché ($17,643.9) alors que  en banque j'ai une autre somme.

Je n'ai pas encore trouvé de la ou cela venait désolé, mais je le signale tout de même.

**Comment by bikouz** [comment]
Il la pas finit pour le moment je pense, c'était à titre d'exemple surement

**Comment by Dev-Assistance** [comment]
Oui avec quelque recherche je pense aussi, mais on sait jamais.

**Comment by bikouz** [comment]
faut demander à @rdlh ce qu'il a fait

**Comment by rdlh** [comment]
Hi @bikouz and @Dev-Assistance, could you please check with [this release (1.1.0)](https://github.com/rdlh/onset-phone/releases/tag/v1.1.0) and keep me posted if it works? Thanks :)

**Comment by Dev-Assistance** [comment]
Now I've just tested everything is good.
